name: FlameHubManager
author: TYSluukie
version: 1.0
main: me.tysluukie.flamehubmanager.main

commands:
    help:
      usage: /<command>
      description: help
    setrank:
      usage: /<command>
      description: setrank
    kitpvp:
      usage: /<command>
      description: kitpvp
    skyblock:
      usage: /<command>
      description: kingdom
    gm:
      usage: /<command>
      description: gamemode
    spawn:
      usage: /<command>
      description: spawn
    setspawn:
      usage: /<command>
      description: setspawn
    startbroadcast:
      usage: /<command>
      description: startbroadcast
    stopbroadcast:
      usage: /<command>
      description: stopbroadcast
    announce:
      usage: /<command>
      description: announce
    shutdown:
      usage: /<command>
      description: shutdown
    lock:
      usage: /<command>
      description: lock
    flamehub:
      usage: /<command>
      description: flamehub